### ISSUE TITLE
Project details

### ISSUE THREAD

**Issue by luis-pomare** [luis-pomare/rails-recipe-app#3]
- Here is the [Link](https://github.com/users/luis-pomare/projects/3/views/1) to our project
- We are two coding partners working on this capstone project

**Comment by zieeco** [comment]
Hi @luis-pomare,

<img height="220" src="https://media3.giphy.com/media/l16AolhwcZQzgDrbGO/giphy.gif"/>


Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- Nice setting up the Kanban board. ✔️
- Descriptive Issue. ✔️


## Required Changes ♻️
_Check the comments below._

- [x] Please, kindly assign a task to the other team member. All the tasks are currently assigned to one team member which is not the goal of using the Kanban board. please, kindly fix this issue.
- [x] Kindly add the name and tag the second team membeer.




## Optional suggestions

- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Abenezer-Tilahun** [comment]
Hi @luis-pomare @SFarida 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻



✔️ Good job for provide the information  about the number of people in their group
✔️ Good Job for provide link to their GitHub project
✔️ Good job for implementing RoR group project: set up your Kanban board 

## Optional suggestions 
 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
